name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build

  check:
    strategy:
      matrix:
        type: [Debug, Release]
        compiler: [gcc9]
        coverage: [false]
        include:
          - type: Debug
            compiler: gcc9
            coverage: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: mkdir build
      - run: nix-shell --argstr compiler ${{ matrix.compiler }} --run "echo ok"
      - run: nix-shell --argstr compiler ${{ matrix.compiler }} --run "cd build && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DENABLE_COVERAGE=${{ matrix.coverage }}"
      - run: nix-shell --argstr compiler ${{ matrix.compiler }} --run "cd build && make check"
      - run: nix-shell --argstr compiler ${{ matrix.compiler }} --run "bash <(curl -s https://codecov.io/bash)"
        if: ${{ matrix.coverage }}
